---
name: industrial

services:
  nodered:
    image: nodered/node-red:latest
    expose:
      - "1880"
    volumes:
      - data:/data
    networks:
      - monitoramento
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"

      # HTTP router
      - "traefik.http.routers.nodered-http.rule=Host(`nodered.teste.local`)"
      - "traefik.http.routers.nodered-http.entrypoints=web"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
    environment:
      - TZ=America/Sao_Paulo
      - NODE_RED_ENABLE_PROJECTS=true
      - NODE_RED_ENABLE_SAFE_MODE=false
    restart: unless-stopped

volumes:
  data:

networks:
  frontend:
    external: true
    name: traefik_public
  monitoramento:
    external: true
    name: monitoramento_backend

