events {}

http {
  resolver 127.0.0.11 valid=5s;

  server {
    listen 80;

    set $upstream demo:8080;
    location / {
      proxy_pass http://$upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}