---
name: management

services:
  portainer:
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik_public
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"  # Remove if you do not intend to use Edge Agents
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"

      # HTTP router (apenas redireciona para HTTPS)
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.fatec.lab`)"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network
  traefik_public:
    external: true
    name: traefik_public