server {
    listen 80;
    server_name site1.fatec.lab;
    
    access_log /var/log/nginx/exemplo_access.log main;
    error_log /var/log/nginx/exemplo_error.log;
    
    location / {
        root /usr/share/nginx/sites/site1;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}