modules:
  if_mib:
    walk: [ifXTable, ipCidrRouteTable, ipAddrTable]
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        lookup: ifDescr
    get:
      - 1.3.6.1.2.1.1.1.0
      - 1.3.6.1.2.1.1.5.0
  ip_mib:
    walk: [ipAddrTable]


